url: ""
title: "Marion Gillot"

collections:
  projects:
    output: true
    permalink: "/:name:output_ext"

defaults:
  - scope:
      path: ""
      type: projects
    values:
      permalink: "/:name:output_ext"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CNAME